### ISSUE TITLE
Incorrect Filename in the FDC3 for Glue42 Core documentation 

### ISSUE THREAD

**Issue by arpanoid** [Glue42/docs#69]
There seems to be an incorrect filename in your documentation for including [FDC3 for Glue42 Core](https://core-docs.glue42.com/getting-started/fdc3-compliance/index.html#fdc3_for_glue42_core).

The correct URL for the file is:

`https://unpkg.com/@glue42/fdc3@3.2.3/dist/fdc3.umd.js`

**Comment by arjunah** [comment]
Hi, thanks for your input. Closing this issue as it's not in the correct repo for the Glue42 Core docs, and also because currently Glue42 Core is being rebranded and all code and documentation is currently being reorganized and moved to new repos. There will be no new updates to the existing Glue42 Core documentation, but this link will be fixed in the new rebranded documentation.
